local player = game.Players.LocalPlayer
local camera = game.Workspace.CurrentCamera

local function playScreamer()
    local screamerGui = Instance.new("ScreenGui")
    screamerGui.Parent = player.PlayerGui

    local image = Instance.new("ImageLabel")
    image.Parent = screamerGui
    image.Size = UDim2.new(1, 0, 1, 0)
    image.Position = UDim2.new(0, 0, 0, 0)
    image.Image = "rbxassetid://118383493320430" 
    image.BackgroundTransparency = 1
    image.ScaleType = Enum.ScaleType.Stretch

    local screamerSound = Instance.new("Sound")
    screamerSound.Parent = player
    screamerSound.SoundId = "rbxassetid://4849128127" 
    screamerSound.Volume = 1000
    screamerSound:Play()

    for i = 1, 30 do
        camera.CFrame = camera.CFrame * CFrame.Angles(math.rad(math.random(-5, 5)), math.rad(math.random(-5, 5)), 0)
        wait(0.05)
    end

    wait(3)
    screamerGui:Destroy()
    screamerSound:Destroy()
end

wait(5)
playScreamer()

print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
print("nigger")
